name: manual_camera_example
description: Demonstrates how to use the camera plugin.

dependencies:
  manual_camera:
    path: ../
  path_provider: ^0.5.0
  flutter:
    sdk: flutter
  video_player: ^0.10.0
  e2e: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4 <2.0.0"
